#! /bin/sh

/bin/systemctl 2>/dev/null | grep -q '\-\.mount'
#echo "result=$?"
if [ "$?" = "0" ]; then
    return 0
else 
    return 1
fi

if systemctl is-active playout; then
    systemctl stop playout
fi
systemctl disable playout

#DEBHELPER#
exit 0
